---
abstract: 'Provides a Reflex Stream object that can use POE::Filters'
author:
  - 'Nicholas R. Perez <nperez@cpan.org>'
build_requires:
  POE::Filter::Line: 0
  Socket: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Reflexive-Stream-Filtering
requires:
  Moose: 0
  Moose::Role: 0
  POE::Filter::Stream: 0
  Reflex::Event: 0
  Reflex::Stream: 0
resources:
  repository: git://nickandperla.net/reflexive-stream-filtering.git
version: 1.122150
